version: '3'
services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/run/tailscale:/var/run/tailscale
    depends_on:
      - backend
      - frontend
    networks:
      - virtual_network_webservice1

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - virtual_network_webservice1

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - virtual_network_webservice1

#     environment:
#       MONGO_URL: mongodb://mongo:27017/mydatabase
#     depends_on:
#       - mongo
# 
#   mongo:
#     image: mongo:latest
#     user: root
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
# 
# volumes:
#   mongo-data:
#     driver: local


networks:
  virtual_network_webservice1:
    driver: bridge