name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - build

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Harbor
      run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login -u ${{ secrets.HARBOR_USERNAME }} --password-stdin harbor.k8s.666lab.org

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: harbor.k8s.666lab.org/webservice1/webservice1-front:latest

    - name: Logout from Harbor
      run: docker logout harbor.k8s.666lab.org
